name: Tests

on: 
  - push
  - pull_request

jobs:
  autoTests:
    name: Run auto tests, make coverage and publish it to CodeClimate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: use node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: install project
        run: make install

      - name: Run auto tests
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: 395a9a32f38a9c530dc7649f650cceadccf8b1aecf7a04464ff14c34cb9ea406
        with:
          coverageCommand: npm run test:coverage
          debug: true